baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lander Wells'
theme = 'kachka'

refLinksErrorLevel = 'warning'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  email = "landerwells@gmail.com"
  github = "https://github.com/landerwells"
  linkedin = "https://www.linkedin.com/in/landerwells"

[markup]
  [markup.highlight]
    lineNos = false # line numbers
    guessSyntax = true
    noClasses = false

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", ":fileModTime", "lastmod"]
  publishDate = ["publishDate", "date"]
