baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lander Wells'

refLinksErrorLevel = 'warning'
disableKinds = ['rss']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  email = "landerwells@gmail.com"
  github = "https://github.com/landerwells"
  linkedin = "https://www.linkedin.com/in/landerwells"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod"]
  publishDate = ['publishDate']
