baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lander Wells'
theme = 'kachka'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  email = "landerwells@gmail.com"
  github = "https://github.com/landerwells"
  linkedin = "https://www.linkedin.com/in/landerwells"
