# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder for an example

name = "Neko"
license = "MIT"

homepage = "https://github.com/landerwells/neko"

[author]
    name = "Lander Wells"
    homepage = "https://www.landerwells.com/"

[original]
    author = "Nicolas P. Rougier"
    homepage = "https://www.labri.fr/perso/nrougier/"
